### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by SGevorg**

### CODE REVIEW

**Comment by bittlingmayer** [comment]
Maybe instead add http://mathschool.ysu.am/mss2018/ and along with it https://deeplanguageclass.github.io (one section of the summer school)?

NLP Guide is linked from the https://deeplanguageclass.github.io anway, and NLP Guide is not any more specific to Yerevan than say the top books on NLP.

**Comment by SGevorg** [comment]
Made the changes to include the summer school and the ML for NLP as a resource. please merge if it's good enough

**Comment by SGevorg** [comment]
Do you think it should be added in the events also? https://mlevn.org/events/ I feel two ways on that.
Also moved from "Materials" to "Courses > ISTC"

**Comment by bittlingmayer** [comment]
Actually we received other PRs, since merged, to add it to Education and Events.

**Pull request closed without merging**
